name: CI

on:
  push:
    branches: [master]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
      - run: cargo fmt --all -- --check

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - 1.63.0
          - stable
          - nightly
    env:
      ETHERCAT_PATH: ../ethercat-git
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          components: clippy

      - name: Set up IgH repo
        run: |
          git clone https://gitlab.com/etherlab.org/ethercat ethercat-git
          cd ethercat-git
          git checkout stable-1.5
          ./bootstrap
          ./configure --disable-8139too

      - run: cargo clippy --all-targets
      - run: cargo build --all-targets
